name: Bearer

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: '35 16 * * 2'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  bearer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Report
        id: report
        uses: bearer/bearer-action@v2
        with:
          format: sarif
          output: results.sarif
          exit-code: 0

      # NEW: normalize SARIF 'results' to be an array ([] when empty)
      - name: Normalize SARIF
        run: |
          jq '(.runs[]?.results) |= (if type == "array" then . else [] end)' results.sarif > results.fixed.sarif
          mv results.fixed.sarif results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
