jobs:
  eslint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: yarn install --frozen-lockfile

      # Make formatter resolvable from ./node_modules, but don't modify package.json/lockfile
      - name: Install SARIF formatter (no save)
        run: npm i -D --no-save @microsoft/eslint-formatter-sarif@3

      - name: ESLint with SARIF
        run: |
          npx eslint . \
            --format=@microsoft/eslint-formatter-sarif \
            --output-file=eslint-results.sarif \
            --max-warnings=0

      - name: Upload to GitHub Security
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
