name: ESLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '32 12 * * 4'

jobs:
  eslint:
    name: Run ESLint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install SARIF formatter
        run: yarn add --dev @microsoft/eslint-formatter-sarif

      - name: Run ESLint (Flat Config)
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: |
          yarn eslint . \
            --no-error-on-unmatched-pattern \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif \
          || echo '{"version":"2.1.0","runs":[]}' > eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
