name: Deploy to jsDelivr

on:
  push:
    branches:
      - main

# Default: lock down the token for all jobs
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # This job must push to the repo (build branch), so grant only what's needed
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy dist folder to build branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: build
          force_orphan: true
